version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/devops-on-demand

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements/test.txt
      - save_cache:
          paths:
            - ~/venv
          key: v1-dependencies-{{ checksum "requirements/test.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            pip install -r requirements/test.txt
            pytest
            # COVERALLS_REPO_TOKEN env var set in CircleCI web UI
            coveralls
